### ISSUE TITLE
WOFF1 ED still missing

### ISSUE THREAD

**Issue by svgeesus** [caribouW3/huit#2]
Despite [adding the WOFF1 GH repo](https://github.com/caribouW3/huit/commit/37a1cd0595ede479d0da3081a9240091e4af177b), WOFF1 is still [listed as unknown](https://caribouw3.github.io/huit/report.html)

![image](https://user-images.githubusercontent.com/2506926/124173974-76fa0f80-dab4-11eb-9959-b952adf048fe.png)

**Comment by caribouW3** [comment]
My bad, generated report from the old json.
Fixed!
